"""
Evaluate trained DeepDeFF models and generate visualizations.

This script loads the results generated by `train_deepdeff.py`, including
the metrics CSV and prediction files. It generates a summary table
and several plots (average MAPE, actual vs predicted, training history)
to replicate and compare against the findings in the DeepDeFF paper.

Paper reported results for comparison:
- SGSC best: DeepDeFF BGRU, avg MAPE 34.87% (2 timestamps)
- Without derived features: LSTM avg MAPE ~44%
- Hybrid CNN-LSTM: avg MAPE 40.38%
"""

import os
import argparse
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from pathlib import Path
import json

# Set publication quality plotting parameters
try:
    plt.style.use('seaborn-v0_8-paper')
except:
    plt.style.use('seaborn-paper')

sns.set_theme(style="whitegrid")
plt.rcParams.update({
    'font.size': 12,
    'axes.titlesize': 14,
    'axes.labelsize': 12,
    'xtick.labelsize': 10,
    'ytick.labelsize': 10,
    'legend.fontsize': 10,
    'figure.titlesize': 16,
})

# Paper's reported results
PAPER_RESULTS = {
    'DeepDeFF BGRU (2 timestamps)': 34.87,
    'LSTM (No derived features)': 44.0,
    'Hybrid CNN-LSTM': 40.38
}

def load_results(results_dir):
    """
    Load results CSV and locate prediction files.
    
    Args:
        results_dir (str): Directory containing the results from training.
        
    Returns:
        pd.DataFrame: Summary results.
        dict: Mapping of (model, customer) to prediction file paths.
    """
    results_path = os.path.join(results_dir, "model_results.csv")
    if not os.path.exists(results_path):
        raise FileNotFoundError(f"Results file not found at {results_path}")
        
    results_df = pd.read_csv(results_path)
    
    # Locate prediction npz files
    predictions = {}
    preds_dir = os.path.join(results_dir, "predictions")
    if os.path.exists(preds_dir):
        for f in os.listdir(preds_dir):
            if f.endswith('.npz'):
                parts = f.replace('.npz', '').split('_')
                if len(parts) >= 2:
                    model = parts[0]
                    customer = parts[1]
                    predictions[(model, customer)] = os.path.join(preds_dir, f)
                    
    history = {}
    history_dir = os.path.join(results_dir, "history")
    if os.path.exists(history_dir):
        for f in os.listdir(history_dir):
            if f.endswith('.json'):
                parts = f.replace('.json', '').split('_')
                if len(parts) >= 2:
                    model = parts[0]
                    customer = parts[1]
                    with open(os.path.join(history_dir, f), 'r') as fp:
                        history[(model, customer)] = json.load(fp)
                        
    return results_df, predictions, history

def generate_summary_table(results_df, output_dir):
    """
    Generate and save a summary table of MAPE per customer per model variant.
    
    Args:
        results_df (pd.DataFrame): Training results containing MAPE.
        output_dir (str): Output directory for evaluation files.
    """
    print("\n--- Generating Results Summary Table ---")
    if 'Model' not in results_df.columns or 'Customer' not in results_df.columns or 'MAPE' not in results_df.columns:
        print("Required columns missing in results dataframe. Need Model, Customer, MAPE.")
        return
        
    pivot_table = results_df.pivot(index='Customer', columns='Model', values='MAPE')
    pivot_table.loc['Average'] = pivot_table.mean()
    
    output_path = os.path.join(output_dir, "mape_summary_table.csv")
    pivot_table.to_csv(output_path)
    print(f"Summary table saved to {output_path}")
    print("\nMAPE Summary Table:")
    print(pivot_table)
    return pivot_table

def plot_average_mape(pivot_table, output_dir):
    """
    Plot the average MAPE comparing model variants and paper baseline.
    
    Args:
        pivot_table (pd.DataFrame): The summary pivot table containing averages.
        output_dir (str): Output directory for plots.
    """
    if pivot_table is None or 'Average' not in pivot_table.index:
        return
        
    avg_mape = pivot_table.loc['Average'].to_dict()
    
    models = list(avg_mape.keys())
    mapes = list(avg_mape.values())
    
    # Add paper results
    for k, v in PAPER_RESULTS.items():
        models.append(f"Paper: {k}")
        mapes.append(v)
        
    plt.figure(figsize=(12, 6))
    bars = sns.barplot(x=models, y=mapes, palette="viridis")
    
    plt.title("Average MAPE by Model Variant")
    plt.ylabel("MAPE (%)")
    plt.xlabel("Model")
    plt.xticks(rotation=45, ha='right')
    
    # Add value labels on top of bars
    for bar in bars.patches:
        bars.annotate(f'{bar.get_height():.2f}%', 
                     (bar.get_x() + bar.get_width() / 2., bar.get_height()), 
                     ha='center', va='center', 
                     xytext=(0, 9), 
                     textcoords='offset points')
                     
    plt.tight_layout()
    plt.savefig(os.path.join(output_dir, "average_mape_comparison.png"), dpi=300)
    plt.close()
    
def plot_actual_vs_predicted(results_df, predictions, output_dir, top_n=5):
    """
    Plot actual vs predicted load for best and worst performing customers.
    
    Args:
        results_df (pd.DataFrame): Training results containing MAPE.
        predictions (dict): Mapping to prediction npz files.
        output_dir (str): Output directory for plots.
        top_n (int): Number of top/bottom customers to plot.
    """
    if results_df.empty or not predictions:
        print("No results or predictions found to plot actual vs predicted.")
        return
        
    best_model = results_df.groupby('Model')['MAPE'].mean().idxmin()
    print(f"Best overall model based on average MAPE: {best_model}")
    
    model_results = results_df[results_df['Model'] == best_model].sort_values(by='MAPE')
    
    if len(model_results) == 0:
        return
        
    best_customers = model_results.head(top_n)['Customer'].tolist()
    worst_customers = model_results.tail(top_n)['Customer'].tolist()
    
    def _plot_customers(customers, title_suffix, filename_suffix):
        for cust in customers:
            if (best_model, cust) not in predictions:
                continue
                
            pred_file = predictions[(best_model, cust)]
            data = np.load(pred_file)
            y_true = data['y_true']
            y_pred = data['y_pred']
            
            # Plot only a subset (e.g., first 500 hours) for clarity
            subset_len = min(500, len(y_true))
            
            plt.figure(figsize=(15, 5))
            plt.plot(y_true[:subset_len], label='Actual', alpha=0.7)
            plt.plot(y_pred[:subset_len], label='Predicted', alpha=0.7)
            plt.title(f"Actual vs Predicted Load ({best_model}) - Customer {cust} ({title_suffix})")
            plt.xlabel("Time steps")
            plt.ylabel("Normalized Load")
            plt.legend()
            plt.tight_layout()
            plt.savefig(os.path.join(output_dir, f"act_vs_pred_{best_model}_cust_{cust}_{filename_suffix}.png"), dpi=300)
            plt.close()

    _plot_customers(best_customers, "Best Performing", "best")
    _plot_customers(worst_customers, "Worst Performing", "worst")

def plot_training_history(history, output_dir):
    """
    Plot training and validation loss curves.
    
    Args:
        history (dict): Dictionary mapping (model, customer) to history dicts.
        output_dir (str): Output directory for plots.
    """
    if not history:
        print("No training history found.")
        return
        
    # Plot history for a few selected examples
    count = 0
    for (model, cust), hist in history.items():
        if count >= 5:  # Limit to 5 plots
            break
            
        if 'loss' not in hist or 'val_loss' not in hist:
            continue
            
        plt.figure(figsize=(10, 5))
        plt.plot(hist['loss'], label='Training Loss')
        plt.plot(hist['val_loss'], label='Validation Loss')
        plt.title(f"Learning Curve - {model} (Customer {cust})")
        plt.xlabel("Epoch")
        plt.ylabel("Loss (MSE)")
        plt.legend()
        plt.tight_layout()
        plt.savefig(os.path.join(output_dir, f"learning_curve_{model}_cust_{cust}.png"), dpi=300)
        plt.close()
        count += 1

def main():
    args = parse_args()
    
    os.makedirs(args.output_dir, exist_ok=True)
    
    print(f"Loading results from {args.results_dir}...")
    try:
        results_df, predictions, history = load_results(args.results_dir)
    except Exception as e:
        print(f"Error loading results: {e}")
        return
        
    pivot_table = generate_summary_table(results_df, args.output_dir)
    plot_average_mape(pivot_table, args.output_dir)
    plot_actual_vs_predicted(results_df, predictions, args.output_dir, args.top_n)
    plot_training_history(history, args.output_dir)
    
    print(f"\nEvaluation complete. Outputs saved to {args.output_dir}")

if __name__ == "__main__":
    main()
